### ISSUE TITLE
Doesn't open the app, also when i downloaded It says that is a virus

### ISSUE THREAD

**Issue by MrxLeo** [hypolas/rawAccelGraph#1]
Doesn't open the app, also when i downloaded it says that is a virus, so basically when i open It, It doesn't open.

**Comment by hypolas** [comment]
Helle MrxLeo,

I just try on https://www.virustotal.com/gui/file/8d9def4a1b338280227b9e183a12cf4e6ce0177e35f01f3ba762baccdb1677f5/detection

But it a false positive.

![image](https://user-images.githubusercontent.com/96924650/182234161-7de9e2e9-eb6e-4bca-b82b-2fabaa9863ae.png)

**Comment by MrxLeo** [comment]
Well, Thanks for the clarify, but It doesn't open i Turned off the Antivirus And i click to open but It doesn't open, i don't know if if because the .exe, the compiler or what but It doesn't open i tried on a lot of computers.
